## Sonar Server
sonar.host.url=http://sonarqube:9000/
sonar.login=...

## About Project
sonar.projectKey=mypythonproject
sonar.projectName=mypythonproject
sonar.sourceEncoding=UTF-8

## Source Code Management
sonar.scm.enabled=true
sonar.scm.provider=git


## SonarScanner Config
sonar.verbose=false
sonar.log.level=INFO
sonar.showProfiling=false
sonar.projectBaseDir=/usr/src/
sonar.working.directory=/tmp/

## Quality Gates
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300

## Python
sonar.language=py
sonar.sources=src
sonar.tests=test
sonar.inclusions=**/*.py
sonar.exclusions=**/migrations/**,**/*.pyc,**/__pycache__/**
sonar.python.coverage.reportPaths=.tmp/coverage.xml,.tmp/cobertura.xml
sonar.python.bandit.reportPaths=.tmp/bandit.json
sonar.python.pylint.reportPaths=.tmp/pylint.txt
sonar.python.flake8.reportPaths=.tmp/flake8.txt
